version: '3'
services:
  mysql:
    image: mariadb:10.5
    container_name: sarah-joias_mysql
    ports:
      - '3306:3306'
    volumes:
      - sarah-db:/var/lib/mysql
      #- ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 123
  php:
    build:
      context: ./php
    container_name: sarah-joias_php
    ports: 
      - '8888:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - teste=oi
volumes:
  sarah-db:
    